### ISSUE TITLE
Background color field doesn't update on project load

### ISSUE THREAD

**Issue by RollinSafary** [koreezgames/phaser-particle-editor#69]
After loading saved project, that has changed background color, editor is applying the color, but on field stays #000000 color code

**Comment by RollinSafary** [comment]
done

**Comment by saqsun** [comment]
@RollinSafary the problem is still there.

<img width="1427" alt="screen shot 2017-10-13 at 8 13 40 pm" src="https://user-images.githubusercontent.com/1752099/31555686-0bc86728-b053-11e7-9ad2-e5130b45133a.png">

**Comment by RollinSafary** [comment]
fixed
